# Generated by Django 5.2.8 on 2025-11-12 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the attendee/registration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendee',
                'verbose_name_plural': 'Attendees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_capacity', models.PositiveIntegerField(default=0, help_text="0 =  use the venue's default capacity")),
                ('image', models.ImageField(blank=True, upload_to='event_images', verbose_name='Event Image')),
                ('status', models.CharField(choices=[('UP', 'Upcoming'), ('OG', 'Ongoing'), ('CP', 'Completed'), ('CC', 'Cancelled')], default='UP', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(default='Standard', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='events', to='myapp.eventtag')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RG', 'Registered'), ('WL', 'Waitlist'), ('CC', 'Cancelled')], default='RG', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='myapp.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='myapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('postcode', models.CharField(blank=True, max_length=60)),
                ('max_capacity', models.PositiveIntegerField(default=0, help_text='Maximum people allowed at the venue')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'indexes': [models.Index(fields=['city'], name='myapp_venue_city_a0332c_idx'), models.Index(fields=['name'], name='myapp_venue_name_4117a1_idx')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='myapp.venue'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['phone_number'], name='myapp_atten_phone_n_18a4ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('user', 'phone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('attendee', 'event')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='myapp_event_start_d_3a253a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='myapp_event_status_599d71_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='myapp_event_event_t_59ef94_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue'], name='myapp_event_venue_i_c23a0a_idx'),
        ),
    ]
