# Generated by Django 6.0 on 2025-12-09 17:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import myapp.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=20)),
                ('postcode', models.CharField(help_text='Format: 12345', max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a valid Malysian postcode', regex='^\\d{5}$')])),
                ('max_capacity', models.PositiveIntegerField(default=0, help_text='Maximum people allowed at the venue')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='VenueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, help_text='First and Last Name', max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Used for login', max_length=11, null=True, unique=True)),
                ('dob', models.DateField(blank=True, help_text='Format "YYYY-MM-DD"', null=True, verbose_name='Date of Birth')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the User', null=True)),
                ('wants_notifications', models.BooleanField(default=False, help_text='Determines whether the user receives whatsapp notifications')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', myapp.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField(help_text='Will be truncated to the nearest 5 minute interval', verbose_name='Start Time')),
                ('end_datetime', models.DateTimeField(help_text='Will be truncated to the nearest 5 minute interval', verbose_name='End Time')),
                ('event_capacity', models.PositiveIntegerField(help_text='Will be limited to the max venue capacity')),
                ('image', models.ImageField(blank=True, upload_to='media/event_images', verbose_name='Event Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='myapp.eventtag')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='myapp.venue')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RG', 'Registered'), ('WL', 'Waitlist')], default='RG', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='myapp.event')),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='myapp.venuetag', verbose_name='Venue Tag'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='myapp_user_phone_n_38d3c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('dob', 'phone_number')},
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('attendee', 'event')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='myapp_event_start_d_3a253a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='myapp_event_event_t_59ef94_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue'], name='myapp_event_venue_i_c23a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['state'], name='myapp_venue_state_2e1167_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='myapp_venue_name_4117a1_idx'),
        ),
    ]
