# Generated by Django 6.0 on 2025-12-09 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(help_text='Will be truncated to the nearest 5 minute interval', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(help_text='Will be truncated to the nearest 5 minute interval', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postcode',
            field=models.CharField(help_text='Format: 12345', max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a valid Malysian postcode', regex='^\\d{5}$')]),
        ),
    ]
