# Generated by Django 5.2.8 on 2025-12-08 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venue',
            name='myapp_venue_city_a0332c_idx',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(default='Johor', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_capacity',
            field=models.PositiveIntegerField(help_text='Will be limited to the max venue capacity'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a valid Malysian postcode', regex='^\\d{5}$')]),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['state'], name='myapp_venue_state_2e1167_idx'),
        ),
    ]
