# Generated by Django 6.0 on 2025-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_event_end_datetime_alter_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_notifications',
            field=models.BooleanField(default=False, help_text='Determines whether the user receives whatsapp notifications'),
        ),
    ]
