# Generated by Django 5.2.8 on 2025-12-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_venue_myapp_venue_city_a0332c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
