# Generated by Django 5.2.8 on 2025-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_event_end_datetime_alter_event_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/event_images', verbose_name='Event Image'),
        ),
    ]
