# Generated by Django 5.2.8 on 2025-12-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_event_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='myapp_event_status_599d71_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('RG', 'Registered'), ('WL', 'Waitlist')], default='RG', max_length=2),
        ),
    ]
