# Generated by Django 5.2.8 on 2025-12-08 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_event_myapp_event_status_599d71_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 8, 14, 15, 41, 47035), verbose_name='End Time'),
        ),
    ]
