# Generated by Django 5.2.8 on 2025-12-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_event_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='First and Last Name', max_length=30, null=True),
        ),
    ]
