# Generated by Django 5.2.8 on 2025-12-08 15:30

import myapp.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_user_username_alter_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', myapp.managers.UserManager()),
            ],
        ),
    ]
